services:
  loumo:
    container_name: loumo
    build:
      context: ./loumo-api
      dockerfile: Dockerfile
    command: sh -c "
      until nc -z mysql_loumo 3306; do
      echo '⏳ Waiting for MySQL...';
      sleep 2;
      done &&
      npx prisma migrate deploy &&
      npx prisma generate &&
      npm run build && npm run start"
    restart: unless-stopped
    environment:
      NODE_ENV: "dev"
      PORT: 5000
      BASE_URL: "http://localhost"

      FRONTEND_URL: "http://localhost:3000"

      PAWAPAY_BASE_URL: "https://api.sandbox.pawapay.io"
      PAWAPAY_API_TOKEN: "eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6IjUzMTciLCJtYXYiOiIxIiwiZXhwIjoyMDY1ODU2NzU1LCJpYXQiOjE3NTAzMjM5NTUsInBtIjoiREFGLFBBRiIsImp0aSI6IjU0YWNlYzhlLWY5ZTMtNDE5YS1iOGIwLTM0NjQ5ZGI5MzU5MiJ9.f9EpjHcwXTbXoggaD5cCbkJ9rPoRm3M1k4q2eo1lbfYS4lHMOAI-2DV_6hxpX7Ula12P6BHSoPgi5UgNDiMgdw"

      # MAIN_DATABASE_URL: "file:./dev.db"
      MAIN_DATABASE_URL: "mysql://root:krest@mysql_loumo:3306/loumo"
      LOG_DATABASE_URL: "mongodb://mongo_loumo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2"
      JWT_SECRET: "your_jwt_secret"

      SMTP_USER: "info@le-carino.com"
      SMTP_PASS: "admin@carino2024"
      MYSQLDB: "mysql://root:krest@mysql:3306/loumo"
    ports:
      - "5000:5000"
    networks:
      - caddy-net
    depends_on:
      - mysql_loumo

  mongo_loumo:
    container_name: mongo_loumo
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: loumo-db
    volumes:
      - /root/backup/loumo/mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - caddy-net

  mysql_loumo:
    container_name: mysql_loumo
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: krest
      MYSQL_DATABASE: loumo
      MYSQL_PASSWORD: krest
    ports:
      - "3317:3306"
    volumes:
      - /root/backup/loumo/mysql-data:/var/lib/mysql
    networks:
      - caddy-net

networks:
  caddy-net:
    name: caddy-net
    external: true
# volumes:
#   mongo-data: {}
#   mysql-data: {}
# correct deployment
