services:
  loumo:
    container_name: loumo
    build:
      context: ./loumo-api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      PAWAPAY_BASE_URL: ${PAWAPAY_BASE_URL}
      PAWAPAY_API_TOKEN: ${PAWAPAY_API_TOKEN}
      MAIN_DATABASE_URL: ${MAIN_DATABASE_URL}
      LOG_DATABASE_URL: ${LOG_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      DB_HOST: ${DB_HOST}
    volumes:
      - /root/backup/loumo/api-data:/app/uploads
    ports:
      - "5001:5000"
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    networks:
      - caddy-net

  mongo_loumo:
    container_name: mongo_loumo
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: loumo-db
    volumes:
      - /root/backup/loumo/mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - caddy-net

  # mysql_loumo:
  #   container_name: mysql_loumo
  #   image: mysql:8
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: krest
  #     MYSQL_DATABASE: loumo
  #     MYSQL_PASSWORD: krest
  #   ports:
  #     - "3317:3306"
  #   # volumes:
  #   #   - /root/backup/loumo/mysql-data:/var/lib/mysql
  #   networks:
  #     - app-network

  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #     MYSQL_DATABASE: loumo
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #   ports:
  #     - "3307:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   networks:
  #     - caddy-net


networks:
  caddy-net:
    driver: bridge
    attachable: true
# volumes:
#   mongo-data: {}
#   mysql-data: {}
# correct deployment
