services:
  loumo:
    container_name: loumo
    build:
      context: ./loumo-api
      dockerfile: Dockerfile
    command: sh -c "
      npx prisma migrate deploy &&
      npx prisma generate &&
      npm run build && npm run start"
    restart: unless-stopped
    environment:
      NODE_ENV: "dev"
      PORT: 5000
      BASE_URL: "http://localhost"

      FRONTEND_URL: "http://localhost:3000"

      PAWAPAY_BASE_URL: "https://api.sandbox.pawapay.io"
      PAWAPAY_API_TOKEN: "eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6IjUzMTciLCJtYXYiOiIxIiwiZXhwIjoyMDY1ODU2NzU1LCJpYXQiOjE3NTAzMjM5NTUsInBtIjoiREFGLFBBRiIsImp0aSI6IjU0YWNlYzhlLWY5ZTMtNDE5YS1iOGIwLTM0NjQ5ZGI5MzU5MiJ9.f9EpjHcwXTbXoggaD5cCbkJ9rPoRm3M1k4q2eo1lbfYS4lHMOAI-2DV_6hxpX7Ula12P6BHSoPgi5UgNDiMgdw"

      # MAIN_DATABASE_URL: "file:./dev.db"
      MAIN_DATABASE_URL: "mysql://u241574545_loumoServer:Krest.Loumo1@62.72.35.227:3306/u241574545_loumoshop"
      LOG_DATABASE_URL: "mongodb://mongo_loumo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2"
      JWT_SECRET: "your_jwt_secret"

      SMTP_USER: "info@loumo.com"
      SMTP_PASS: "admin@loumo2024"
      MYSQLDB: "mysql://u241574545_loumoServer:Krest.Loumo1@62.72.35.227:3306/u241574545_loumoshop"
    ports:
      - "5001:5000"
    networks:
      - caddy-net

  mongo_loumo:
    container_name: mongo_loumo
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: loumo-db
    volumes:
      - /root/backup/loumo/mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - caddy-net

  # mysql_loumo:
  #   container_name: mysql_loumo
  #   image: mysql:8
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: krest
  #     MYSQL_DATABASE: loumo
  #     MYSQL_PASSWORD: krest
  #   ports:
  #     - "3317:3306"
  #   # volumes:
  #   #   - /root/backup/loumo/mysql-data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  caddy-net:
    driver: bridge
    attachable: true
# volumes:
#   mongo-data: {}
#   mysql-data: {}
# correct deployment
