services:
  loumo:
    container_name: loumo
    build:
      context: ./loumo-api
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate dev --name init && npx prisma generate && npm run build && npm run start"
    restart: unless-stopped
    environment:
      NODE_ENV: "dev"
      PORT: 5000
      BASE_URL: "http://localhost"

      FRONTEND_URL: "http://localhost:3000"

      PAWAPAY_BASE_URL: "https://api.sandbox.pawapay.io"
      PAWAPAY_API_TOKEN: "eyJraWQiOiIxIiwiYWxnIjoiRVMyNTYifQ.eyJ0dCI6IkFBVCIsInN1YiI6IjUzMTciLCJtYXYiOiIxIiwiZXhwIjoyMDY1ODU2NzU1LCJpYXQiOjE3NTAzMjM5NTUsInBtIjoiREFGLFBBRiIsImp0aSI6IjU0YWNlYzhlLWY5ZTMtNDE5YS1iOGIwLTM0NjQ5ZGI5MzU5MiJ9.f9EpjHcwXTbXoggaD5cCbkJ9rPoRm3M1k4q2eo1lbfYS4lHMOAI-2DV_6hxpX7Ula12P6BHSoPgi5UgNDiMgdw"

      MAIN_DATABASE_URL: "file:./dev.db"
      LOG_DATABASE_URL: "mongodb://mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2"
      JWT_SECRET: "your_jwt_secret"

      SMTP_USER: "info@le-carino.com"
      SMTP_PASS: "admin@carino2024"
      MYSQLDB: "mysql://root:krest@mysql:3306/loumo"
    ports:
      - "5000:5000"
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: loumo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loumo_db
      MYSQL_USER: loumo_user
      MYSQL_PASSWORD: loumo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    attachable: true

volumes:
  mongo-data: {}
# correct deployment
